# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f282590dbc95d3d3f0aaef77c58a1eff7e89b3e2192731422df41e3faa0eab6bdeab1b0a4efb0284c139bd31b44b9cc251ee6635691ca2ed98587c31ee957e9d

test:
  secret_key_base: 8569fb866a61536b9135b7bbc7172c162f8e793257d59af5064b0b5fd133296b6446b282f35a7ea9fd13c40521cc2a8281a86419ab781b03d19c4e13f04cb7d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
